import { NavBar, Footer, SideBar } from "@/components";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import {
  AuthProvider,
  OpenBarProvider,
  LoaderProvider,
  FdaVersionsProvider,
  TableSelectProvider,
} from "@/contexts";
import { setupAuthHook, setupScrapeVersionsHook } from "@/http/utils-server";

export const metadata = {
  title: "RXScope",
  description: "Generated by RXScope",
  icons: {
    icon: "https://www.iconninja.com/files/631/966/414/repository-github-icon.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [
    hasCreds,
    defaultCredentials,
    hasUsername,
    defaultUsername,
    hasRole,
    defaultRole,
    hasUserId,
    defaultUserId,
  ] = await setupAuthHook();
  const [] = await setupScrapeVersionsHook();
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-
awesome.min.css"
          rel="stylesheet"
          integrity="sha384-
wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
          crossOrigin="anonymous"
        ></link>
      </head>
      <body className="overflow-x-hidden overflow-y-hidden">
        <ThemeProvider attribute="class">
          <LoaderProvider>
            <OpenBarProvider>
              <AuthProvider
                initialData={{
                  hasCreds,
                  defaultCredentials,
                  hasUsername,
                  defaultUsername,
                  hasRole,
                  defaultRole,
                  hasUserId,
                  defaultUserId,
                }}
              >
                <FdaVersionsProvider>
                  <SideBar>
                    <TableSelectProvider>
                      <div className="h-[100vh] overflow-y-auto">
                        <NavBar />
                        {children}
                        <Footer />
                      </div>
                    </TableSelectProvider>
                  </SideBar>
                </FdaVersionsProvider>
              </AuthProvider>
            </OpenBarProvider>
          </LoaderProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
