import { NavBar, Footer, SideBar } from "@/components";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import {
  AuthProvider,
  OpenBarProvider,
  LoaderProvider,
  FdaVersionsProvider,
  TableSelectProvider,
} from "@/contexts";
import { cookies } from "next/headers";
import { dummy_cred } from "@/utils";

export const metadata = {
  title: "RXScope",
  description: "Generated by RXScope",
  icons: {
    icon: "https://www.iconninja.com/files/631/966/414/repository-github-icon.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = cookies();
  const credsCookie = cookie.get("credentials");
  const hasCredsCookie = credsCookie && credsCookie.value != "";
  let defaultCredentials = "{}";
  if (process.env.NEXT_PUBLIC_ENV_NAME === "local-dev") {
    console.log("1. Dummy creds for testing without cognito");
    const dummy_username = "leo.leung.rxscope";
    const act = await dummy_cred(dummy_username);
    defaultCredentials = JSON.stringify({
      AccessToken: act,
      ExpiresIn: 3600,
      IdToken: "",
      RefreshToken: "",
      TokenType: "Bearer",
    });
  } else {
    defaultCredentials = hasCredsCookie ? credsCookie.value : "{}";
  }
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-
awesome.min.css"
          rel="stylesheet"
          integrity="sha384-
wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
          crossOrigin="anonymous"
        ></link>
      </head>
      <body className="overflow-x-hidden overflow-y-hidden">
        <ThemeProvider attribute="class">
          <LoaderProvider>
            <OpenBarProvider>
              <AuthProvider defaultCredentials={defaultCredentials}>
                <FdaVersionsProvider>
                  <SideBar>
                    <TableSelectProvider>
                      <div className="h-[100vh] overflow-y-auto">
                        <NavBar />
                        {children}
                        <Footer />
                      </div>
                    </TableSelectProvider>
                  </SideBar>
                </FdaVersionsProvider>
              </AuthProvider>
            </OpenBarProvider>
          </LoaderProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
